### GENERAL SETTINGS ###

# Site settings
title: Damian Calabresi
description: "Damian Calabresi personal website"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.dcalabresi.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: google-plus
    url: https://plus.google.com/+DamianCalabresi21
  - title: twitter
    url: https://twitter.com/damiancalabresi
  - title: linkedin
    url: https://www.linkedin.com/pub/damian-calabresi/32/901/586
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Buenos Aires,
    - Argentina.
email: damiancalabresi@gmail.com
tel: +54 9 11 3125-4333


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Damian Calabresi
    position: CEO
    text: Computer Engineer. Java Developer. South Park fan
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:damiancalabresi@gmail.com
      - title: twitter
        url: https://twitter.com/damiancalabresi

# Clients information. Shown on Home and About pages.
clients:
  - name: client
    img: client01.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "About Damian Calabresi"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "A testimonial"
    author: Damian Calabresi
    position: Web site owner